Consultas:

In [10]:
#Librerias a utilizar

import pandas as pd

In [11]:
df_items_consulta = pd.read_parquet(r"C:\Users\jotad\OneDrive\Escritorio\proyecto\df_final_sample.parquet")

In [12]:
df_reviews_consulta = pd.read_csv(r'C:\Users\jotad\OneDrive\Escritorio\proyecto\df_reviews_final.csv')

In [13]:
df_games_consulta = pd.read_csv(r'C:\Users\jotad\OneDrive\Escritorio\proyecto\steam_games_final.csv')

In [14]:
# Seleccionar las columnas necesarias de cada DataFrame


import pandas as pd

# Supongamos que las columnas que necesitas ya existen en los DataFrames
# Aquí asumiré que no hay una columna común para combinar los DataFrames

# Seleccionar columnas de df_reviews
df_reviews_selected = df_reviews_consulta[['recommend', 'sentiment_analysis', 'user_id']]

# Seleccionar columnas de df_items
df_items_selected = df_items_consulta[['user_id', 'playtime_forever']]

# Seleccionar columnas de df_games
df_games_selected = df_games_consulta[['developer', 'year', 'price', 'id', 'genres']]

# Combinar DataFrames sin especificar una clave
df_para_consultas = pd.concat([df_reviews_selected, df_items_selected, df_games_selected], axis=1)

# Ahora 'df_para_consultas' contendrá todas las columnas necesarias

In [15]:
df_para_consultas

,recommend,sentiment_analysis,user_id,user_id,playtime_forever,developer,year,price,id,genres
0,1.0,2.0,76561197970982479,jadziatuvok,0.0,Kotoshiro,2018.0,4.99,761140.0,"['Action', 'Casual', 'Indie', 'Simulation', 'S..."
1,1.0,2.0,js41637,rhysdog,207.0,Secret Level SRL,2018.0,0,643980.0,"['Free to Play', 'Indie', 'RPG', 'Strategy']"
2,1.0,2.0,evcentric,Hirutha,2139.0,Poolians.com,2017.0,0,670290.0,"['Casual', 'Free to Play', 'Indie', 'Simulatio..."
3,1.0,2.0,doctr,fereleth,0.0,彼岸领域,2017.0,0.99,767400.0,"['Action', 'Adventure', 'Casual']"
4,1.0,2.0,maplemage,76561198006541747,0.0,Trickjump Games Ltd,2018.0,3.99,772540.0,"['Action', 'Adventure', 'Simulation']"
...,...,...,...,...,...,...,...,...,...,...
49995,NaN,NaN,NaN,76561198015238503,41.0,NaN,NaN,NaN,NaN,NaN
49996,NaN,NaN,NaN,Chrazzari,2.0,NaN,NaN,NaN,NaN,NaN
49997,NaN,NaN,NaN,76561198068611843,106.0,NaN,NaN,NaN,NaN,NaN
49998,NaN,NaN,NaN,76561198046755491,409.0,NaN,NaN,NaN,NaN,NaN
49999,NaN,NaN,NaN,Red_Kn1ght,0.0,NaN,NaN,NaN,NaN,NaN

In [16]:
df_para_consultas = df_para_consultas.to_csv(r"C:\Users\jotad\OneDrive\Escritorio\proyecto\df_para_consultas.csv")